In [1]:
!pip3.8 install numpy

  Using cached numpy-1.21.2-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.8 MB)


In [3]:
import numpy as np

In [8]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
a = np.arange(1,11).reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
!pip3.8 install pandas

     |████████████████████████████████| 11.5 MB 20.5 MB/s eta 0:00:01    |██████████████████████████▍     | 9.5 MB 20.5 MB/s eta 0:00:01
     |████████████████████████████████| 503 kB 154.5 MB/s eta 0:00:01


In [7]:
import pandas as pd

In [14]:
data = pd.DataFrame(a) 
data

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [2]:
import numpy as np
import pandas as pd

In [3]:
# 산술 평균 계산
x = [1,2,3,4,5]
print(np.mean(x))
print(np.array(x).mean())
print(pd.Series(x).mean())

3.0
3.0
3.0


In [4]:
# 이진 변수에 대한 평균
x = [1,0,0,0,1]
print(np.mean(x))

0.4


In [24]:
# 조화 평균 : 변화량의 평균을 구할 때 사용
from scipy.stats import *
x = np.array([0.1,0.2,0.3,0.4,0.5])
print(len(x) / np.sum(1/x))
print(hmean(x)) # 역수의 평균의 역수를 구할 때에만 hmean을 사용

0.21897810218978103
0.21897810218978103


In [7]:
# 절사 평균이 필요한 이유
income = np.random.normal(2000000,500000,100)
print(np.mean(income))

1952250.918709312


In [8]:
imcome = np.append(income, 10**9)
print(np.mean(income))

1952250.918709312


In [25]:
trim_mean(income,0.2) #[20~80%]

1944868.8105022765

In [11]:
pip install scipy

     |████████████████████████████████| 28.4 MB 19.6 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [17]:
# 실습 - 대표 통계량
from scipy import stats
np.random.seed(0) # randim.seed를 주는 이유: 아래 randint로 만든 값을 계속 유지하기 위해
                  # 머신러닝 할 때 생성한 데이터를 계속 유지해야 모델 만들 수 있음
                  # 다음에 똑같은 데이터 생성하려면 반드시 똑같은 seed 숫자 줘야 함 = 0
data = np.random.randint(0,100,10000)
print(data)
mean = np.mean(data) ; print("평균값: ", mean.round(2))
median = np.median(data) ; print("중앙값: ", median)
mode = stats.mode(data) ; print("최빈값: {} ({})".format(mode[0][0],mode[1][0]))

[44 47 64 ... 39 72 48]
평균값:  49.17
중앙값:  49.0
최빈값: 3 (125)


In [21]:
# pandas로 대푯값 구하기
import pandas as pd
import numpy as np
np.random.seed(0)
data = np.random.randint(0,100,10000)
df = pd.Series(data)
print(df)
mean = df.mean() ; print("평균값:{:.2f}".format(mean)) # 또는 round(mean,2) 도 ok
median = df.median() ; print("중앙값: ", median)
mode = df.mode() ; print("최빈값:",mode) 
# scipy는 통계쪽에 최적화되어 있어 빈도수가 동일한 숫자가 여러 개이면 모두 반환해줌
#        + 최빈 숫자와 빈도수를 모두 출력 가능
# pandas는 최빈 숫자가 여러 개인 경우 사용하기 곤란 + 빈도수는 출력해주지 않음
#        + 최빈 숫자와 해당 index만 출력해 줌

0       44
1       47
2       64
3       67
4       67
        ..
9995     7
9996    29
9997    39
9998    72
9999    48
Length: 10000, dtype: int64
평균값:49.17
중앙값:  49.0
최빈값: 0    3
dtype: int64
